version: '2'
services:
  mqtt:
    build: ./mqtt
    restart: always
  bridge:
    build: ./bridge
    privileged: true
    restart: always
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    cap_add: 
      - SYS_RAWIO
    depends_on:
      - mqtt