FROM resin/%%BALENA_MACHINE_NAME%%-python

COPY app.py /
COPY SX127x/* /SX127x/
RUN pip install paho-mqtt

COPY entrypoint.sh /
RUN chmod 755 /entrypoint.sh
ENTRYPOINT ["/bin/sh", "-c"]
CMD ["/entrypoint.sh"]