FROM resin/%%BALENA_MACHINE_NAME%%-python

COPY entrypoint.sh /
RUN chmod 755 /entrypoint.sh

COPY bridge.py /
COPY SX127x/* /SX127x/
RUN pip install paho-mqtt RPi.GPIO spidev

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["/entrypoint.sh"]